In [1]:
import numpy as np
a = np.random.randn(5)

In [2]:
print(a)

[-0.66489976 -1.36161657 -0.69879553 -0.16254283 -0.40729352]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-0.66489976 -1.36161657 -0.69879553 -0.16254283 -0.40729352]


In [5]:
print(np.dot(a, a.T))

2.9767147524635003


In [6]:
#DO INSTEAD
a = np.random.randn(5,1)
print(a)

[[ 0.13271691]
 [-1.09679247]
 [ 0.08569106]
 [-1.21037622]
 [-0.33348866]]


In [7]:
print(a.T)

[[ 0.13271691 -1.09679247  0.08569106 -1.21037622 -0.33348866]]


In [8]:
print(np.dot(a, a.T))

[[ 0.01761378 -0.14556291  0.01137265 -0.16063739 -0.04425959]
 [-0.14556291  1.20295371 -0.09398531  1.32753152  0.36576785]
 [ 0.01137265 -0.09398531  0.00734296 -0.10371843 -0.028577  ]
 [-0.16063739  1.32753152 -0.10371843  1.46501061  0.40364675]
 [-0.04425959  0.36576785 -0.028577    0.40364675  0.11121469]]
